# Generated by Django 4.1.7 on 2023-02-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='FISH')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon nomer')),
                ('sponsor_type', models.CharField(choices=[('JSH', 'Jismoniy shaxs'), ('YSH', 'Yuridik shaxs')], max_length=15, verbose_name='Homiy turi')),
                ('amont_of_money', models.IntegerField(verbose_name='Homiylik summasi')),
                ('spent_money', models.IntegerField(verbose_name='Sarflangan pul miqdori')),
                ('payment_type', models.CharField(choices=[('Uzcard', 'Uzcard'), ('Humo', 'Humo')], max_length=15, verbose_name='To`lov turi')),
                ('organization', models.IntegerField(blank=True, null=True, verbose_name='Kompaiya nomi')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('Moderation', 'Moderatsiyada'), ('Approved', 'Tasdiqlangan'), ('Canceled', 'Bekor qilingan')], max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
    ]
