# Generated by Django 4.1.7 on 2023-02-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Homiy', 'verbose_name_plural': 'Homiylar'},
        ),
    ]
