# Generated by Django 4.1.7 on 2023-03-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_alter_sponsor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kompaiya nomi'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='spent_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sarflangan pul miqdori'),
        ),
    ]
