# Generated by Django 4.1.7 on 2023-03-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_alter_sponsor_organization_alter_sponsor_spent_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('Moderation', 'Moderatsiyada'), ('Approved', 'Tasdiqlangan'), ('Canceled', 'Bekor qilingan')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
