# Generated by Django 4.1.7 on 2023-02-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition_for_legal_entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='FISH')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon nomer')),
                ('amont_of_money', models.IntegerField(verbose_name='Homiylik summasi')),
                ('organization', models.IntegerField(blank=True, null=True, verbose_name='Kompaiya nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Petition_for_physical_entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='FISH')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon nomer')),
                ('amont_of_money', models.IntegerField(verbose_name='Homiylik summasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amont_of_money', models.IntegerField(verbose_name='Ajratilgan pul miqdori')),
                ('sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.sponsor', verbose_name='Homiy')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Talaba')),
            ],
        ),
    ]
