# Generated by Django 4.1.7 on 2023-02-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name': 'Ehson', 'verbose_name_plural': 'Ehsonlar'},
        ),
        migrations.AlterModelOptions(
            name='petition_for_legal_entity',
            options={'verbose_name': 'Yuridik shaxs uchun ariza', 'verbose_name_plural': 'Jismoniy shaxs uchun arizalar'},
        ),
        migrations.AlterModelOptions(
            name='petition_for_physical_entity',
            options={'verbose_name': 'Yuridik shaxs uchun ariza', 'verbose_name_plural': 'Yuridik shaxs uchun arizalar'},
        ),
    ]
