# Generated by Django 4.1.7 on 2023-02-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='FISH')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon nomer')),
                ('degree', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr')], max_length=15, verbose_name='Darajasi')),
                ('contract', models.IntegerField(verbose_name='Kontrakti')),
                ('amont_of_money', models.IntegerField(verbose_name='Ajratilgan pul miqdori')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.university')),
            ],
        ),
    ]
