# Generated by Django 4.1.7 on 2023-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Universitet', 'verbose_name_plural': 'Universitetlar'},
        ),
        migrations.AlterField(
            model_name='student',
            name='amont_of_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ajratilgan pul miqdori'),
        ),
    ]
