# Generated by Django 4.1.7 on 2023-03-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amont_of_money',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ajratilgan pul miqdori'),
        ),
    ]
